### ISSUE TITLE
why using p_prime = 1 - np.sqrt(1 - p) in SBM_multiclass?

### ISSUE THREAD

**Issue by FeiGSSS** [zhengdao-chen/GNN4CD#5]
hi,
Thanks for your contribution! I'm wondering why you have to using `p_prime = 1 - np.sqrt(1 - p)` for  SBM_multiclass? Is there any mathematical consideration?

**Comment by zhengdao-chen** [comment]
Thanks for the question. The reason is that to generate an undirected graph with a symmetric adjacency matrix, our method is to first sample an asymmetric matrix `W`  and then compute the symmetrized matrix `W = np.maximum(W, W.transpose())`. Because of this, in order to make sure the _symmetric_ `W` created at the end have the desired connectivities `p` and `q`, we need to sample the _asymmetric_ `W` with `p_prime` and `q_prime`.
